### ISSUE TITLE
Feat: Add support for common terminals

### ISSUE THREAD

**Issue by vihu** [Verf/deepwhite.nvim#1]
Hello, thank you for writing this colorscheme! It's very hard to find pleasing light colorschemes for neovim :)

I would really appreciate if you could also add support for some commonly used terminals (specifically wezterm and kitty). Just providing a simple base16 toml file in an `extras` folder would suffice. For reference here's how [nightfox](https://github.com/EdenEast/nightfox.nvim/blob/main/extra/dayfox/nightfox_wezterm.toml) does it.

Thanks!

**Comment by Verf** [comment]
Thank you for your suggestion, i added support for kitty, wezterm, windows terminal and xresources (https://github.com/Verf/deepwhite.nvim/commit/12ccfd0d6ce48f95cf10c3ef936cd39e14188f98). But i'm working on a windows machine and haven't used kitty and wezterm so i'm not sure these would work well :).

**Comment by vihu** [comment]
Great! I think you're missing the first ansi/bright color for wezterm but other than that thank you very much!
