### ISSUE TITLE
Highlighting is lost as the LSP starts up.

### ISSUE THREAD

**Issue by denstiny** [Verf/deepwhite.nvim#10]
https://github.com/Verf/deepwhite.nvim/assets/57088952/896888d2-f212-4673-b9f8-106f1fb967d1

**Comment by denstiny** [comment]
![image](https://github.com/Verf/deepwhite.nvim/assets/57088952/8593f6d5-9cc6-4fbc-80b4-957d705a8fc3)
It seems to be mapped to an incorrect highlight group.

**Comment by Verf** [comment]
Thinks!

**Comment by denstiny** [comment]
6122772426f507c725a2219220fa3cfa00275e7a

The problem still exists

**Comment by Verf** [comment]
> [6122772](https://github.com/Verf/deepwhite.nvim/commit/6122772426f507c725a2219220fa3cfa00275e7a)
> 
> The problem still exists

Hi, please try e33776edca8733329f8cca14ca87fdae03d91dcc, i forget the lsp.type.method.

**Comment by denstiny** [comment]
Thank you, he is perfect now
