### ISSUE TITLE
Feat: Add support for some common bufferline/statusline plugins

### ISSUE THREAD

**Issue by vihu** [Verf/deepwhite.nvim#2]
It would be really nice to have some highlighting support for bufferline/statusline plugins, specifically lualine and barbar. I believe they are used extensively by a lot of neovim users. Thanks!

**Comment by Verf** [comment]
Add https://github.com/Verf/deepwhite.nvim/commit/2d4ad04ad8b6a0dcb81c89f7bd2fcc89d77c19d7 for barbar and https://github.com/Verf/deepwhite.nvim/commit/ba91d74d652983d4f443165e4e825f2992cb71b3 for lualine. Hope you like these minimalist statusline style :)
