### ISSUE TITLE
Blank cursor when used with folke/noice.nvim

### ISSUE THREAD

**Issue by d-3nnis** [Verf/deepwhite.nvim#3]
When using noice.nvim, the cursor seems to disappear, making it really hard to type commands.
![image](https://github.com/Verf/deepwhite.nvim/assets/38957070/6c068c0d-4afe-462e-a65c-66a2e4922842)
![image](https://github.com/Verf/deepwhite.nvim/assets/38957070/8101cf86-f4ac-47a6-8ed5-df11453fc0a6)

**Comment by Verf** [comment]
fix in 99d09bc
![image](https://github.com/Verf/deepwhite.nvim/assets/22053969/4c9eff18-797f-48fe-9a45-f397afde7ac5)
