### ISSUE TITLE
Broken config for wezterm

### ISSUE THREAD

**Issue by vikulikov** [Verf/deepwhite.nvim#9]
ansi and bright arrays should be of length 8 but 7 provided

**Comment by Verf** [comment]
hi, but ansi and bright arrays are length 8 correctly, maybe you shoud check again.


![image](https://github.com/Verf/deepwhite.nvim/assets/22053969/d1d3470a-1d39-41cb-9dfe-f7411c95c64e)

**Comment by vikulikov** [comment]
Oh, sorry. I've probably seen the file from old commit
